source 'https://rubygems.org'

ruby '2.4.2'

gem 'database_cleaner'
gem 'data_mapper'
gem 'dm-migrations'
gem 'dm-postgres-adapter'
gem 'dm-transactions'
gem 'pry'
gem 'rack'
gem 'rubocop'
gem 'sinatra'
gem 'thin'
gem 'rake'
gem 'capybara'
gem 'rspec'
